services:
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - my.main.app.db-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-app:1.0.0
    depends_on:
      - db
      - adminer
    container_name: my-app
    ports:
      - 8090:8085
      - 9001:9001
      
volumes:
  my.main.app.db-data: